version: '3.8'

services:
  laravel:
    build:
      context: ./backend
    ports:
      - "8000:9000" # Port externe:interne
    volumes:
      - ./backend:/var/www # Volume pour synchroniser le code
    env_file:
      - ./backend/.env # Fichier d'environnement Laravel
    depends_on:
      - db

  vue:
    build:
      context: ./frontend
    ports:
      - "8080:80" # Frontend exposé sur le port 8080
    environment:
      - VITE_BACKEND_URL=http://<render-backend-url>:8000 # Utilisez l'URL Render pour le backend Laravel

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
